Repository bsoc-bitbyte/BSoC-Website, pull requests merged in 2024-06, with the labels that each got.

#68 Fixes #65 fix(responsiveness): Fixed the issue and added the desired responsive nature to smaller size screens.
  src/views/Projects.vue
Labels: difficulty : Easy, BSoC'24

#69 fix #64: updated project details for bsoc'24
  src/views/Projects.vue
Labels: difficulty : Easy, BSoC'24

#72 fix #70 : added and refactored toasts on login/signup
  src/App.vue
  src/components/Login.vue
  src/components/Signup.vue
  src/components/ToastComponent.vue
  src/composables/deleteDocuments.js
  src/composables/useToast.js
  src/views/Auth.vue
  src/views/MyPR.vue
Labels: difficulty : Medium, BSoC'24

#74 Fix #66 feat(submit-pr): dynamically fetch all PRs using github api
  src/views/SubmitPR.vue
Labels: difficulty : Hard, BSoC'24

#79 FIxes #76 feat(timer): Added the countdown feature
  src/views/Home.vue
Labels: difficulty : Easy, BSoC'24

#81 Fix #77 fix(result_filter): Filtered out results with zero score in the leaderboard/dashboard
  src/views/Dashboard.vue
Labels: difficulty : Easy, BSoC'24

#82 fix(accordion): correct behavior and improve styling of accordion
  package.json
  src/components/FAQItem.vue
  src/components/FAQS.vue
  src/views/Home.vue
Labels: difficulty : Medium, BSoC'24

#89 Fix #87 fix(frontend): Remove whitespace which is visible at the end of myPR page when opening myPR page in mobile
  src/views/Dashboard.vue
  src/views/MyPR.vue
  src/views/User.vue
Labels: difficulty : Easy, BSoC'24

#90 Fixes #85 - Fixing the issue related to submitting the PRs in the webpage
  src/views/SubmitPR.vue
Labels: difficulty : Medium, BSoC'24
