Repository bsoc-bitbyte/BSoC-Website, pull requests merged in 2024-07, with the labels that each got.

#96 Fix #93: Added pagination in the dashboard page
  src/views/Dashboard.vue
Labels: difficulty : Easy, BSoC'24

#98 fix(bug): error with overlapping modals and mobile sidenav
  src/components/Login.vue
  src/components/Nav.vue
Labels: bug, difficulty : Easy

#99 feat(frontend): Added a search bar in the dashboard page (#94)
  src/assets/fonts/Search.jpg
  src/assets/fonts/searchicon.jpg
  src/assets/searchicon.jpg
  src/views/Dashboard.vue
Labels: good first issue, difficulty : Easy, BSoC'24

#105 feat(landing-page): update responsiveness of landing page
  src/views/LandingPage.vue
Labels: difficulty : Easy, BSoC'24

#104 Fixes #103 feat(enhancement): Replaced timer, updated FAQ
  src/components/FAQS.vue
  src/views/Home.vue
Labels: difficulty : Easy, BSoC'24

#106 feat(loading-skeleton): added loader skeleton in dashboard
  src/views/Dashboard.vue
Labels: difficulty : Easy, BSoC'24

#116 Fix #108 feat(frontend): Updated theme of BSoC Website and removed unnecessary files from assets
  src/App.vue
  src/assets/BsoC logo.svg
  src/assets/Discord.svg
  src/assets/Github.svg
  src/assets/Logo.svg
  src/assets/TPC logo.svg
  src/assets/discord.svg
  src/assets/discord1.svg
  src/assets/explore1.png
  src/assets/explore1.svg
  src/assets/fonts/IstokWeb-Regular.ttf
  src/assets/fonts/PricedownBl-Regular 900.ttf
  src/assets/fonts/Search.jpg
  src/assets/fonts/StargazeStencil.otf
  src/assets/fonts/searchicon.jpg
  src/assets/home-bg.jpg
  src/assets/instagram.svg
  src/assets/main.css
  src/assets/search.svg
  src/assets/searchicon.jpg
  src/components/FAQItem.vue
  src/components/FAQS.vue
  src/components/Footer.vue
  src/components/Login.vue
  src/components/PreLoader.vue
  src/components/Signup.vue
  src/layouts/DashboardLayout.vue
  src/layouts/GeneralLayout.vue
  src/layouts/LandingLayout.vue
  src/router/index.js
  src/views/Dashboard.vue
  src/views/Home.vue
  src/views/LandingPage.vue
  src/views/MyPR.vue
  src/views/Projects.vue
  src/views/SubmitPR.vue
  src/views/User.vue
Labels: difficulty : Hard, BSoC'24

#118 Fixes #117 fix(submit-collab-pr): added additional filter so that collaborators …
  src/views/SubmitPR.vue
Labels: difficulty : Easy, BSoC'24
